### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by wireinet** [jzmstrjp/brackets---color-the-tag-name#1]
HellO! nice plugin! very nice! More information from code! :)
But it is flicker! after, i press button!
smaaaaal flicking...but this is bad...can you, fix this?

**Comment by jzmstrjp** [comment]
Thank you for using.
I wanna fix the bug, too.
I've try it today and yesterday.
But I couldn't.
Because I'm beginner.
But someday, I'll fix the bug.

**Comment by wireinet** [comment]
go ahead!!

**Comment by wireinet** [comment]
After update is  ok!
Great! Thank you!

**Comment by jzmstrjp** [comment]
I fixd this bug, just now!
thank you for advise.
