### ISSUE TITLE
Causes brackets editor to not function properly

### ISSUE THREAD

**Issue by odifek** [jzmstrjp/brackets---color-the-tag-name#2]
Happens most times. Causes the editor to misbehave especially with code completion and color code display in css and html. 
When selecting autocomplete suggestion using enter, the cursor jumps to new line instead of selecting the suggestion. Also color code doesn't display color box on hover anymore. Amongst other issues. I really love the plugin when it's working properly

**Comment by jzmstrjp** [comment]
OK!
I try to fix that bug.

**Comment by jzmstrjp** [comment]
Mmm...
I can't reproduce the bug...
It may be due to compatibility with other plugins.

**Comment by odifek** [comment]
Maybe. Because it used to work smoothly initially

**Comment by jzmstrjp** [comment]
I'm sorry...
I will give up.
Because I can not reproduce it.
