### ISSUE TITLE
A good suggestion to mention: CSS3 substrings

### ISSUE THREAD

**Issue by trendoman** [jzmstrjp/brackets---color-the-tag-name#3]
It's worth noting CSS3 substring attribute selectors
```
[attribute^=value] { /* starts with selector */
/* Styles */
}

[attribute$=value] { /* ends with selector */
/* Styles */
}

[attribute*=value] { /* contains selector */
/* Styles */
}
```

Great to highlight custom CMS-tags, as in:

`[data-tag-name^="cms"]{color: #aaf;}`

It helps with a single string for the whole set of **cms:tagname** tags.

**Comment by jzmstrjp** [comment]
It's nice advice!
I will consider adding it to the README.
