### ISSUE TITLE
How to ignore commented tags?

### ISSUE THREAD

**Issue by vhanla** [jzmstrjp/brackets---color-the-tag-name#5]
`<!-- -->` tags inside comments aren't ignored and colorized

**Comment by jzmstrjp** [comment]
Can I see a screenshot?

**Comment by vhanla** [comment]
![image](https://user-images.githubusercontent.com/1015823/44788634-38071b00-ab60-11e8-8d2d-932da844072d.png)
Tags inside comments are still colorized.

**Comment by vhanla** [comment]
BTW, can it only colorize the tag name excepting attributes?
![image](https://user-images.githubusercontent.com/1015823/44788815-a64bdd80-ab60-11e8-956d-4101f1cdd938.png)

**Comment by jzmstrjp** [comment]
Thanks.
Mmm...
In my environment, tags in comments are not colored.
Could you tell me the name of the theme you are using?

**Comment by vhanla** [comment]
I tested with clean VSCode and only installed this extension using the default theme, but still has the same issue. Maybe is related to VSCode's version or Operating Sytem, I'm using latest VSCode on Windows 10.

![image](https://user-images.githubusercontent.com/1015823/44792795-4f4b0600-ab6a-11e8-83b1-58c2bc69f586.png)

**Comment by jzmstrjp** [comment]
Oh, VSCode!
I was misunderstanding that it is with Adobe Brackets.

**Comment by jzmstrjp** [comment]
This repository is for Adobe Brackets Version...

**Comment by jzmstrjp** [comment]
However, on the VSCode version, Tags in comments are certainly colored.

**Comment by jzmstrjp** [comment]
I will think about it tomorrow.

**Comment by jzmstrjp** [comment]
I am not familiar with developing VSCode extensions, so I probably can't fix it ...!

**Comment by jzmstrjp** [comment]
@vhanla 
I fixd this bug.
